### PR TITLE
Refactor Facebook login

### PR DESCRIPTION
**Pull request by satya164**
NOTE: I've not tested this. But I've been using similar module in prod.

### CODE REVIEW

**Comment by magus** [comment]
This looks like an improvement but I'm actually quite unfamiliar with the Android side of things. Could you post a screenshot of everything working with your fork or increase the confidence I have in merging this somehow?

@lwhiteley : Could you take a look at this?

**Comment by lwhiteley** [comment]
looks fine actually, 

@satya164 can you test this somehow and post a screenshot, just for confirmation.

**Comment by satya164** [comment]
@lwhiteley @magus Will do.

**Comment by buhe** [comment]
Nice, this pr fix some bug. but example code  is dependency rn 0.18+

**Comment by magus** [comment]
@satya164  @lwhiteley 
Merged this along with the updates to the README

**Pull request merged**
