### PR TITLE
Feature: add android support

### PR DESCRIPTION
**Pull request by lwhiteley**
Addresses issue #27 

Setup Docs: https://github.com/lwhiteley/react-native-facebook-login/blob/master/Android.md
component: https://github.com/lwhiteley/react-native-facebook-login/blob/master/android.js

Notes:
- [x] no logout functionality on button  yet (FBLoginManager has a logout api though)

- [x] Button has no state management to know if its logged in/out
- [x] May need to get some of the methods to match whats currently there for iOS

Possible Future Updates:
- [ ] loginBehaviour not configurable yet, will use whatever is available on device or simulator
- [ ] FBLogin is a custom button and not a wrapped version of the Android FBLoginButton (may implement this)
- [ ] Allow [login / logout] content to be configurable

sample reponse on successful login
<a href="http://imgur.com/DQiVyaf"></a>

### CODE REVIEW

**Comment by magus** [comment]
Huge. :tada: :+1: 

Are you planning on addressing the notes you listed or do you think this can be merged before that work is done? Sounds like the first three are all relatively related and just require adding a bit of state.

There might be a way to leverage the existing mock button I created as well and simply reference the Android  native methods. 

https://github.com/magus/react-native-facebook-login/blob/master/example/components/facebook/FBLoginMock.js

**Comment by lwhiteley** [comment]
yea i at least want to add the state for a first release. will look into it

**Comment by magus** [comment]
Okey doke, sounds like others have confirmed it's working. Looking forward to the updates and merge!

**Comment by lwhiteley** [comment]
sorry for the delay folks. State now added to button. can login/logout now .. test away

@magus

**Comment by lwhiteley** [comment]
Features for the Future:
- Allow [login / logout] button content to be configurable

**Comment by pedro** [comment]
Hey! Thanks a lot for this. I'm testing it here and seems to work nicely.

Just sharing a few notes in case it helps others:

- As part of the setup you'll need to add another import to `MainActivity.java`:
  
  ```java
  import android.content.Intent;
  ```

- The interface is a bit different. To use the original package with iOS:
  
  ```js
  FBLogin = require('react-native-facebook-login');
  ```

  But what's proposed here:

  ```js
  var {FBLoginManager, FBLogin} = require('react-native-facebook-login/android');
  ```

  I think this can be fixed quickly with a JS wrapper for Android (`index.android.js`).

**Comment by lwhiteley** [comment]
thanks for the feedback @pedro will make the updates.

@magus did a rebase happen on your master branch?

**Comment by lwhiteley** [comment]
@pedro, feedback fixed .. please see the setup docs

To be consistent, the require statement for android is now 
```js
FBLogin = require('react-native-facebook-login');
```

**Comment by magus** [comment]
I did some cleaning up on source history and some changes for React Native 0.14. Are there any issues or do you think it's good to merge? I think I should make you a contributor as well so you can handle fixes and merge in further changes once it's in. What do you think?

**Comment by lwhiteley** [comment]
yep thats fine @magus 

and its ready for a merge. think folks are fine with it now

**Comment by pedro** [comment]
:+1::+1::+1: works great, diff looks much better – thank you!

**Comment by magus** [comment]
Merged and added @lwhiteley as a collaborator. Thanks again for this PR, huge :+1:

**Pull request merged**
