### PR TITLE
Fix PropTypes warning

### PR DESCRIPTION
**Pull request by maggialejandro**
Use prop-types npm module. React.PropTypes will be removed completely in React 16.

### CODE REVIEW

**Comment by innoc** [comment]
Please merge this PR. 
I just updated my react-native and i get the 'Underfined is not an object _react.PropTypes.array' error. 

Merging this PR will fix it.

**Comment by Peercel** [comment]
@maggialejandro  When will this be merged in. My app is breaking

**Comment by maggialejandro** [comment]
Hi @magus, could you merge this please?

**Comment by zafrirSchop** [comment]
What's the status on this?

**Comment by jnrepo** [comment]
@magus please merge.

**Comment by magus** [comment]
Thanks for taking the time to fix this!

**Pull request merged**
