### PR TITLE
chore: add android setup link to readme

### PR DESCRIPTION
**Pull request by lwhiteley**
[Review on Reviewable](https://reviewable.io/reviews/magus/react-native-facebook-login/38)

### CODE REVIEW

**Comment by magus** [comment]
_[README.md, line 12 \[r1\]](https://reviewable.io:443/reviews/magus/react-native-facebook-login/38#-K3lSij5UtTEKRtBmjrD:-K3lSij5UtTEKRtBmjrE:859580760) ([raw file](https://github.com/magus/react-native-facebook-login/blob/f678f71432e1431589205c84069b019b744ed887/README.md#L12)):_
Instead of a link here maybe we can split the 'Setup' into 'iOS' and 'Android' instead

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/magus/react-native-facebook-login/38)_

**Comment by magus** [comment]
_[README.md, line 133 \[r1\]](https://reviewable.io:443/reviews/magus/react-native-facebook-login/38#-K3lStWMFML1PolkpJI4:-K3lStWMFML1PolkpJI5:165611600) ([raw file](https://github.com/magus/react-native-facebook-login/blob/f678f71432e1431589205c84069b019b744ed887/README.md#L133)):_
## Setup

- [iOS](###ios)
- [Android](Android.md)

### iOS

... <all the existing instructions> ...

 ### Android

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/magus/react-native-facebook-login/38)_

**Comment by magus** [comment]
_[README.md, line 133 \[r1\]](https://reviewable.io:443/reviews/magus/react-native-facebook-login/38#-K3lStWMFML1PolkpJI4:-K3lTLOxR9YDE7HMGxTT:1067629733) ([raw file](https://github.com/magus/react-native-facebook-login/blob/f678f71432e1431589205c84069b019b744ed887/README.md#L133)):_
This comment turned into markdown but basically I'd say we could put a link under setup to keep the table of contents general

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/magus/react-native-facebook-login/38)_

**Comment by magus** [comment]
If you move Android.md under /android and rename is 'README.md' it will render as the README under that directory as well when users click into that directory

---







_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/magus/react-native-facebook-login/38#-:-K3lTU7KjqyJTTg9s_ml:1835651684)_

**Comment by magus** [comment]
Added some comments with reviewable, not critical though can be merged as-is to resolve the issue with an issue to clean up the README later

**Comment by niftylettuce** [comment]
why is this still not in 2 weeks later

**Pull request merged**
