### PR TITLE
chore: namespace android FBLoginManager to MFBLoginManager

### PR DESCRIPTION
**Pull request by lwhiteley**
This change is [Reviewable](https://reviewable.io/reviews/magus/react-native-facebook-login/156)

### CODE REVIEW

**Comment by southernvg** [comment]
*[index.android.js, line 160 at r1](https://reviewable.io:443/reviews/magus/react-native-facebook-login/156#-KRp6btxKODu-ZOqmjeS:-KRp6btyi1j_PwdTk734:buyppmz) ([raw file](https://github.com/magus/react-native-facebook-login/blob/ed4ec985a4b1c7384c2ee216fa11771fdb5ecfad/index.android.js#L160)):*
> ```JavaScript
> 
> export {
>   FBLogin: FBLogin,
> ```

This line is generating​ an error on Android (master)

~/project/node_modules/react-native-facebook-login/index.android.js: Unexpected token (160:9) at index.android.js:160:9

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/magus/react-native-facebook-login/156)*

**Comment by lwhiteley** [comment]
how are you importing the module to use it, everyone else is reporting that its working

are you using 
```
import {FBLogin} from 'react-native-facebook-login'
```

**Comment by lwhiteley** [comment]
i see the error now and fixed it.. thanks

feel free to get the updates

**Comment by southernvg** [comment]
Works great now.  Thank You.

**Comment by AmitPandya007** [comment]
> how are you importing the module to use it, everyone else is reporting that its working
> 
> are you using
> 
> ```
> import {FBLogin} from 'react-native-facebook-login'
> ```

@lwhiteley 
I am using it like this only and I am getting:
 null is not an object FBLoginManager.LoginBehaviors'
and
null is not an object FBLoginManager.Events'
While working with iOS, for android it worked. any help will be really appreciated. Thank you.

**Pull request merged**
