### PR TITLE
Fixed ViewPropTypes.style

### PR DESCRIPTION
**Pull request by adamonkey**
This was causing my iOS app to crash upon start. This has to be changed to accommodate new RN versions.

### CODE REVIEW

**Comment by michael-gillett** [comment]
Getting this merged and released would be awesome

**Comment by rmn528** [comment]
please, merge this

**Comment by tiberiumihai** [comment]
Please merge this one.

**Comment by jnrepo** [comment]
please merge...

this is an issue starting in react-native version `0.49.3` due to react `16`.

**Comment by jeremyeaton89** [comment]
+1

**Comment by jedrivisser** [comment]
+1

**Comment by xmarianox** [comment]
please merge!!! 🙏🏼

**Comment by adamonkey** [comment]
I switched to react-native-fbsdk. It was an easy switch, and the library is maintained by Facebook itself.

**Comment by michaelstokes** [comment]
Hello :) I assume this is why I'm getting this issue here https://stackoverflow.com/questions/47446064/react-native-app-debug-mode-works-fine-release-mode-crashes-app-registry-and-e

`11-23 00:48:17.259: E/ReactNativeJS(20526): Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)`

and

`com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'a.View.propTypes.style'), stack:`

?

Thanks very much

**Comment by patw0929** [comment]
+1

**Comment by longtranista** [comment]
Any progress?

**Comment by dseipp** [comment]
@adamonkey thanks for the tip.  Tired of waiting for updates here.  Gonna switch to react-native-fbsdk as well.

**Comment by alex-melnyk** [comment]
2018-02-20 22:49:34.473178+0200 sharingiscaring[2080:239096] [Crashlytics] Version 3.9.3 (128)
2018-02-20 22:49:34.550766+0200 sharingiscaring[2080:239096] Setting up RNFirebase instance
2018-02-20 22:49:34.671101+0200 sharingiscaring[2080:239096] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-02-20 22:49:34.673063+0200 sharingiscaring[2080:239096] [MC] Reading from public effective user settings.
2018-02-20 22:49:34.695674+0200 sharingiscaring[2080:239178] [Firebase/Analytics][I-ACS023007] Firebase Analytics v.40004000 started
2018-02-20 22:49:34.695837+0200 sharingiscaring[2080:239178] [Firebase/Analytics][I-ACS023008] To disable debug logging set the following application argument: -noFIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2018-02-20 22:49:34.695944+0200 sharingiscaring[2080:239178] [Firebase/Analytics][I-ACS023009] Debug logging enabled
2018-02-20 22:49:34.696214+0200 sharingiscaring[2080:239178] [Firebase/Analytics][I-ACS003007] Successfully created Firebase Analytics App Delegate Proxy automatically. To disable the proxy, set the flag FirebaseAppDelegateProxyEnabled to NO in the Info.plist
2018-02-20 22:49:34.710 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'u.View.propTypes.style')
2018-02-20 22:49:34.711093+0200 sharingiscaring[2080:239174] undefined is not an object (evaluating 'u.View.propTypes.style')
2018-02-20 22:49:34.712 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'u.View.propTypes.style')
2018-02-20 22:49:34.712457+0200 sharingiscaring[2080:239162] Unhandled JS Exception: undefined is not an object (evaluating 'u.View.propTypes.style')
2018-02-20 22:49:34.713 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module (calling runApplication)
2018-02-20 22:49:34.713068+0200 sharingiscaring[2080:239174] Module AppRegistry is not a registered callable module (calling runApplication)
2018-02-20 22:49:34.714210+0200 sharingiscaring[2080:239162] *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not an object (evaluating 'u.View.propTypes.style')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'u.View.prop..., stack:
<unknown>@369:1548
d@2:755
<unknown>@368:2796
d@2:755
<unknown>@366:182
d@2:755
<unknown>@343:282
d@2:755
<unknown>@305:141
d@2:755
<unknown>@12:42
d@2:755
n@2:326
global code@1033:8
'
*** First throw call stack:
(0x181e43164 0x18108c528 0x1025bf830 0x1025bd288 0x181e4aad0 0x181d2936c 0x181d2de1c 0x1025d2948 0x102617274 0x102616fd4 0x10302d2cc 0x10302d28c 0x10303bf80 0x1030307ec 0x10303cf6c 0x103044020 0x181a6af1c 0x181a6ab6c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

You can help for all of us, just merge that commit!

**Comment by jcandrade** [comment]
Please, can u merge this?

**Comment by magus** [comment]
Thanks for reporting this, the fix is out in version 1.6.1!

**Pull request closed without merging**
